### ISSUE TITLE
data contains BOM characters

### ISSUE THREAD

**Issue by atanarro** [konsumer/randopeep#1]
Hi,

If you look at some of the json data (for instance data/name/chinese/male/first.json) the first sample name ("﻿Ah-cy") contains an unexpected BOM character:
`"﻿Ah-cy".charCodeAt(0) === 65279 //instead of an A (65)`

I guess this is not the intended behaviour but an issue.

Thanks for your useful module.

**Comment by konsumer** [comment]
Ugh. I feel like I need to structure a bunch of things better, and strip those weird characters. I think the "remote" version should just get it's wordlists from an HTTP endpoint. I will try to put some love into this, this week. Thanks for the report!

**Comment by konsumer** [comment]
I just did a pretty major overhaul, and I think this is resolved. Let me know if not.
